import type { Metadata } from "next";

import { SectionHeading } from "@/components/section-heading";

export const metadata: Metadata = {
  title: "Terms of Service",
};

const LAST_UPDATED = "January 1, 2026";

export default function TermsOfServicePage() {
  return (
    <article>
      <SectionHeading
        headingId="terms-heading"
        label="Legal"
        headline="Terms of Service"
        description={`Last updated ${LAST_UPDATED}`}
        className="text-left"
      />

      <p className="text-muted-foreground mt-8 text-sm leading-relaxed text-pretty italic">
        This is placeholder content for development purposes and does not
        constitute a binding legal agreement. Replace it with terms reviewed by
        qualified legal counsel before accepting real users or payments.
      </p>

      <div className="mt-10 flex flex-col gap-10">
        <section aria-labelledby="terms-acceptance">
          <h2
            id="terms-acceptance"
            className="text-foreground text-xl font-semibold tracking-tight"
          >
            1. Acceptance of Terms
          </h2>
          <p className="text-muted-foreground mt-3 text-sm leading-relaxed text-pretty">
            By creating an account or otherwise accessing or using Nexona (the
            &ldquo;Service&rdquo;), you agree to be bound by these Terms of
            Service. If you do not agree to these terms, do not use the Service.
            We may update these terms from time to time, and continued use of
            the Service after changes take effect constitutes acceptance of the
            revised terms.
          </p>
        </section>

        <section aria-labelledby="terms-description">
          <h2
            id="terms-description"
            className="text-foreground text-xl font-semibold tracking-tight"
          >
            2. Description of Service
          </h2>
          <p className="text-muted-foreground mt-3 text-sm leading-relaxed text-pretty">
            Nexona is a résumé analysis platform that uses artificial
            intelligence to provide feedback on how a résumé is likely to be
            received by recruiters and automated applicant tracking systems.
            Analyses, suggestions, and any other output generated by the Service
            are provided for informational purposes only and do not guarantee
            any employment outcome, interview, or offer.
          </p>
        </section>

        <section aria-labelledby="terms-accounts">
          <h2
            id="terms-accounts"
            className="text-foreground text-xl font-semibold tracking-tight"
          >
            3. Accounts and Eligibility
          </h2>
          <p className="text-muted-foreground mt-3 text-sm leading-relaxed text-pretty">
            You must provide accurate and complete information when creating an
            account and are responsible for maintaining the confidentiality of
            your login credentials. You are responsible for all activity that
            occurs under your account. You must be at least 16 years old to use
            the Service.
          </p>
        </section>

        <section aria-labelledby="terms-acceptable-use">
          <h2
            id="terms-acceptable-use"
            className="text-foreground text-xl font-semibold tracking-tight"
          >
            4. Acceptable Use
          </h2>
          <p className="text-muted-foreground mt-3 text-sm leading-relaxed text-pretty">
            You agree not to upload content you do not have the right to share,
            attempt to reverse-engineer or disrupt the Service, exceed
            reasonable request volumes, or use the Service to build a competing
            product. We reserve the right to suspend or terminate accounts that
            violate these terms.
          </p>
        </section>

        <section aria-labelledby="terms-subscriptions">
          <h2
            id="terms-subscriptions"
            className="text-foreground text-xl font-semibold tracking-tight"
          >
            5. Subscriptions and Payment
          </h2>
          <p className="text-muted-foreground mt-3 text-sm leading-relaxed text-pretty">
            Paid plans are billed in advance on a recurring basis as described
            at the time of purchase. Fees are non-refundable except where
            required by law. You may cancel a paid plan at any time, and
            cancellation takes effect at the end of the current billing period.
          </p>
        </section>

        <section aria-labelledby="terms-ip">
          <h2
            id="terms-ip"
            className="text-foreground text-xl font-semibold tracking-tight"
          >
            6. Intellectual Property
          </h2>
          <p className="text-muted-foreground mt-3 text-sm leading-relaxed text-pretty">
            You retain all rights to the résumé content and other material you
            upload. You grant us a limited license to process that content
            solely to provide the Service to you. The Service itself, including
            its design, code, and branding, remains the property of Nexona.
          </p>
        </section>

        <section aria-labelledby="terms-disclaimer">
          <h2
            id="terms-disclaimer"
            className="text-foreground text-xl font-semibold tracking-tight"
          >
            7. Disclaimer of Warranties
          </h2>
          <p className="text-muted-foreground mt-3 text-sm leading-relaxed text-pretty">
            The Service is provided &ldquo;as is&rdquo; without warranties of
            any kind, express or implied. AI-generated output may contain
            inaccuracies, and we do not warrant that the Service will be
            uninterrupted, error-free, or fit for any particular purpose.
          </p>
        </section>

        <section aria-labelledby="terms-liability">
          <h2
            id="terms-liability"
            className="text-foreground text-xl font-semibold tracking-tight"
          >
            8. Limitation of Liability
          </h2>
          <p className="text-muted-foreground mt-3 text-sm leading-relaxed text-pretty">
            To the maximum extent permitted by law, Nexona will not be liable
            for any indirect, incidental, special, or consequential damages
            arising from your use of the Service, including any employment or
            career outcome related to its use.
          </p>
        </section>

        <section aria-labelledby="terms-termination">
          <h2
            id="terms-termination"
            className="text-foreground text-xl font-semibold tracking-tight"
          >
            9. Termination
          </h2>
          <p className="text-muted-foreground mt-3 text-sm leading-relaxed text-pretty">
            You may stop using the Service and delete your account at any time.
            We may suspend or terminate your access if you violate these terms
            or if we discontinue the Service, with notice where reasonably
            practicable.
          </p>
        </section>

        <section aria-labelledby="terms-law">
          <h2
            id="terms-law"
            className="text-foreground text-xl font-semibold tracking-tight"
          >
            10. Governing Law
          </h2>
          <p className="text-muted-foreground mt-3 text-sm leading-relaxed text-pretty">
            These terms are governed by the laws of the jurisdiction in which
            Nexona is established, without regard to conflict-of-law principles.
          </p>
        </section>

        <section aria-labelledby="terms-contact">
          <h2
            id="terms-contact"
            className="text-foreground text-xl font-semibold tracking-tight"
          >
            11. Contact
          </h2>
          <p className="text-muted-foreground mt-3 text-sm leading-relaxed text-pretty">
            Questions about these terms can be sent to{" "}
            <a
              href="mailto:legal@nexona.app"
              className="text-foreground underline underline-offset-3 hover:no-underline"
            >
              legal@nexona.app
            </a>
            .
          </p>
        </section>
      </div>
    </article>
  );
}
